<a href="https://colab.research.google.com/github/JingfengSteven/NAM_trail/blob/trail_1/July_Uncertainty_Projectsadssd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/JingfengSteven/givemesomecredit

fatal: destination path 'givemesomecredit' already exists and is not an empty directory.


In [2]:
import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()
from givemesomecredit import models as nam_models

import os.path as osp
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import sklearn
import heapq
import copy

In [3]:
orgdata=pd.read_csv("givemesomecredit/cs-training.csv")
orgdata=orgdata.dropna(axis=0)
orgdata.head()

Unnamed: 0  SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
0           1                 1                              0.766127   45   
1           2                 0                              0.957151   40   
2           3                 0                              0.658180   38   
3           4                 0                              0.233810   30   
4           5                 0                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     2   0.802982         9120.0   
1                                     0   0.121876         2600.0   
2                                     1   0.085113         3042.0   
3                                     0   0.036050         3300.0   
4                                     1   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                               13                        0   
1                                4                        0   
2                                2                        1   
3                                5                        0   
4                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                             6                                     0   
1                             0                                     0   
2                             0                                     0   
3                             0                                     0   
4                             1                                     0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [4]:
data=orgdata

In [5]:
x=data.iloc[:,2:data.shape[1]]
y=data.iloc[:,1]
x.insert(data.shape[1]-2, 'label', y)
x.head()

RevolvingUtilizationOfUnsecuredLines  age  \
0                              0.766127   45   
1                              0.957151   40   
2                              0.658180   38   
3                              0.233810   30   
4                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     2   0.802982         9120.0   
1                                     0   0.121876         2600.0   
2                                     1   0.085113         3042.0   
3                                     0   0.036050         3300.0   
4                                     1   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                               13                        0   
1                                4                        0   
2                                2                        1   
3                                5                        0   
4                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                             6                                     0   
1                             0                                     0   
2                             0                                     0   
3                             0                                     0   
4                             1                                     0   

   NumberOfDependents  label  
0                 2.0      1  
1                 1.0      0  
2                 0.0      0  
3                 0.0      0  
4                 0.0      0

In [6]:
x=np.array(x)
x.shape

(120269, 11)

In [7]:
x[:,[0,2]]=x[:,[2,0]]
x[:,[1,8]]=x[:,[8,1]]
x[:,[2,6]]=x[:,[6,2]]
x[:,[3,4]]=x[:,[4,3]]
x[:,[4,9]]=x[:,[9,4]]
x1=x
x1 = np.delete(x1, np.where
    (x1[:,0] >= 20), axis=0)
x1 = np.delete(x1, np.where
    (x1[:,1] >= 20), axis=0)
x1 = np.delete(x1, np.where
    (x1[:,2] >= 20), axis=0)
x1[:,0][x1[:,0]>=4]=4
x1[:,1][x1[:,1]>=4]=4
x1[:,2][x1[:,2]>=4]=4

x1[:,3][(x1[:,3]>=0)&(x1[:,3]<2500)]=5
x1[:,3][(x1[:,3]>=2500)&(x1[:,3]<5000)]=4
x1[:,3][(x1[:,3]>=5000)&(x1[:,3]<7500)]=3
x1[:,3][(x1[:,3]>=7500)&(x1[:,3]<10000)]=2
x1[:,3][(x1[:,3]>=10000)&(x1[:,3]<50000)]=1
x1[:,3][x1[:,3]>=50000]=0

x1[:,4][x1[:,4]>=5]=5

X=x1[:,0:len(x1[0])-1]
Y=x1[:,-1]

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(
      X, Y, test_size=0.3, random_state=42)

In [9]:
tf.compat.v1.reset_default_graph()
Model_1 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_1(X)
Model_1.load_weights('./Model/my_checkpoint1')

tf.compat.v1.reset_default_graph()
Model_2 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_2(X)
Model_2.load_weights('./Model/my_checkpoint2')

tf.compat.v1.reset_default_graph()
Model_3 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_3(X)
Model_3.load_weights('./Model/my_checkpoint3')

tf.compat.v1.reset_default_graph()
Model_4 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_4(X)
Model_4.load_weights('./Model/my_checkpoint4')

tf.compat.v1.reset_default_graph()
Model_5 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_5(X)
Model_5.load_weights('./Model/my_checkpoint5')

tf.compat.v1.reset_default_graph()
Model_6 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_6(X)
Model_6.load_weights('./Model/my_checkpoint6')

tf.compat.v1.reset_default_graph()
Model_7 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_7(X)
Model_7.load_weights('./Model/my_checkpoint7')

tf.compat.v1.reset_default_graph()
Model_8 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_8(X)
Model_8.load_weights('./Model/my_checkpoint8')

tf.compat.v1.reset_default_graph()
Model_9 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_9(X)
Model_9.load_weights('./Model/my_checkpoint9')

tf.compat.v1.reset_default_graph()
Model_10 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation = 'sigmoid'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
]
)
Model_10(X)
Model_10.load_weights('./Model/my_checkpoint10')

In [10]:
class MyCredit:
  def __init__ (self,data):
    self.id=hasher(data)
    self.data=data
    self.var=0
    self.value=Model_load_value(data)

  def __lt__ (self, other):
    return self.value > other.value

  def get_id(self):
    return self.id

  def get_data(self):
    return self.data

  def get_var(self):
    return self.var

  def get_value(self):
    return self.value

In [11]:
def hasher(data):
  Arr=np.array(data)
  str_arr = np.array_str(Arr)

  str_arr = str_arr.replace('[', '').replace(']', '').replace('\n', '')

  Hash=hash(str_arr)
  return Hash

In [12]:
def Model_load_var(X):

  predict1=Model_1(np.array([X]))
  predict2=Model_2(np.array([X]))
  predict3=Model_3(np.array([X]))
  predict4=Model_4(np.array([X]))
  predict5=Model_5(np.array([X]))
  predict6=Model_6(np.array([X]))
  predict7=Model_7(np.array([X]))
  predict8=Model_8(np.array([X]))
  predict9=Model_9(np.array([X]))
  predict10=Model_10(np.array([X]))

  su=[]
  su.append(np.array(predict1))
  su.append(np.array(predict2))
  su.append(np.array(predict3))
  su.append(np.array(predict4))
  su.append(np.array(predict5))
  su.append(np.array(predict6))
  su.append(np.array(predict7))
  su.append(np.array(predict8))
  su.append(np.array(predict9))
  su.append(np.array(predict10))

  su=np.array(su)

  su=su.reshape(10,1)
  vari=np.var(su,axis=0,ddof=1)

  return vari

In [13]:
def Model_load_value(X):

  mean=(Model_1(np.array([X]))+Model_2(np.array([X]))+Model_3(np.array([X]))+Model_4(np.array([X]))+Model_5(np.array([X]))+Model_6(np.array([X]))+Model_7(np.array([X]))+Model_8(np.array([X]))+Model_9(np.array([X]))+Model_10(np.array([X])))/10

  return mean

In [14]:
def calc_var(data):
  Var=Model_load_var(data)
  return Var

In [15]:
def calc_value(data):
  Mean=Model_load_value(data)
  return Mean

In [16]:
def find_next1(now):
  data_next=copy.deepcopy(now)
  data_next.data[0]=data_next.data[0]-1

  sign=1
  if(data_next.data[0]<0 or data_next.data[1]<0 or data_next.data[2]<0 or data_next.data[3]<0 or data_next.data[4]<0):
    sign=-1
  data_next.id=hasher(data_next.data)
 # data_next.var=calc_var(data_next.data)
 # data_next.value=calc_value(data_next.data)
  return data_next,sign

In [17]:
def find_next2(now):
  data_next=copy.deepcopy(now)

  data_next.data[1]=data_next.data[1]-1

  sign=1
  if(data_next.data[0]<0 or data_next.data[1]<0 or data_next.data[2]<0 or data_next.data[3]<0 or data_next.data[4]<0):
    sign=-1
  data_next.id=hasher(data_next.data)
 # data_next.var=calc_var(data_next.data)
 # data_next.value=calc_value(data_next.data)
  return data_next,sign

In [18]:
def find_next3(now):
  data_next=copy.deepcopy(now)

  data_next.data[2]=data_next.data[2]-1

  sign=1
  if(data_next.data[0]<0 or data_next.data[1]<0 or data_next.data[2]<0 or data_next.data[3]<0 or data_next.data[4]<0):
    sign=-1
  data_next.id=hasher(data_next.data)
 # data_next.var=calc_var(data_next.data)
#  data_next.value=calc_value(data_next.data)
  return data_next,sign

In [19]:
def find_next4(now):
  data_next=copy.deepcopy(now)

  data_next.data[3]=data_next.data[3]-1

  sign=1
  if(data_next.data[0]<0 or data_next.data[1]<0 or data_next.data[2]<0 or data_next.data[3]<0 or data_next.data[4]<0):
    sign=-1
  data_next.id=hasher(data_next.data)
#  data_next.var=calc_var(data_next.data)
#  data_next.value=calc_value(data_next.data)
  return data_next,sign

In [20]:
def find_next5(now):
  data_next=copy.deepcopy(now)

  data_next.data[4]=data_next.data[4]-1
  sign=1
  if(data_next.data[0]<0 or data_next.data[1]<0 or data_next.data[2]<0 or data_next.data[3]<0 or data_next.data[4]<0):
    sign=-1
  data_next.id=hasher(data_next.data)
 # data_next.var=calc_var(data_next.data)
 # data_next.value=calc_value(data_next.data)
  return data_next,sign

In [21]:
def check_uncertainty(point,hold,boundary):
  reflec=False
  flag=[]
  now=MyCredit(point)
  que=[]
  heapq.heappush(que, now)
  flag.append(now.id)
  iterm=0
  for i in range(1,len(boundary)):
    bod=MyCredit(boundary[i])
    heapq.heappush(que, bod)
    flag.append(bod.id)

  while(len(que)!=0):
    now=heapq.heappop(que)
    now.var=Model_load_var(now.data)
    iterm+=1
 #   print(now.data[0:5],np.array(now.value),np.array(now.var))
    data1,sign1=find_next1(now)
    data2,sign2=find_next2(now)
    data3,sign3=find_next3(now)
    data4,sign4=find_next4(now)
    data5,sign5=find_next5(now)

    if(data1.id not in flag and sign1==1):
     # data1.var=calc_var(data1.data)
      data1.value=calc_value(data1.data)
      flag.append(data1.id)
      heapq.heappush(que, data1)
    if(data2.id not in flag and sign2==1):
     # data2.var=calc_var(data2.data)
      data2.value=calc_value(data2.data)
      flag.append(data2.id)
      heapq.heappush(que, data2)
    if(data3.id not in flag and sign3==1):
     # data3.var=calc_var(data3.data)
      data3.value=calc_value(data3.data)
      flag.append(data3.id)
      heapq.heappush(que, data3)
    if(data4.id not in flag and sign4==1):
     # data4.var=calc_var(data4.data)
      data4.value=calc_value(data4.data)
      flag.append(data4.id)
      heapq.heappush(que, data4)
    if(data5.id not in flag and sign5==1):
     # data5.var=calc_var(data5.data)
      data5.value=calc_value(data5.data)
      flag.append(data5.id)
      heapq.heappush(que, data5)

    if(now.var<hold):
      reflec=True
      return now,reflec,iterm

  return now,reflec,iterm

In [22]:
def find_boundary(check):
  prex1=check[0]
  prex2=check[1]
  prex3=check[2]
  boundary=[]
  #x1<x2<x3
  for x_1 in range(5):
    for x_2 in range(5):
      for x_3 in range(5):
        if(x_3<=prex3 and x_2+x_3<=prex2+prex3 and x_1+x_2+x_3==prex1+prex2+prex3):
          boundary.append([x_1,x_2,x_3,check[3],check[4],check[5],check[6],check[7],check[8],check[9]])
  return boundary

In [23]:
Y_1=Model_1(X)
Y_2=Model_2(X)
Y_3=Model_3(X)
Y_4=Model_4(X)
Y_5=Model_5(X)
Y_6=Model_6(X)
Y_7=Model_7(X)
Y_8=Model_8(X)
Y_9=Model_9(X)
Y_10=Model_10(X)
su=[]
su.append(Y_1)
su.append(Y_2)
su.append(Y_3)
su.append(Y_4)
su.append(Y_5)
su.append(Y_6)
su.append(Y_7)
su.append(Y_8)
su.append(Y_9)
su.append(Y_10)

In [24]:
su=np.array(su)
su.size
su=su.reshape(10,-1)
vari=np.var(su,axis=0,ddof=1)
vari

array([4.7302004e-03, 3.2870703e-05, 1.3429449e-04, ..., 4.5455749e-06,
       2.0891343e-06, 2.2912944e-05], dtype=float32)

In [25]:
vari1=vari[vari>=0.001]

In [26]:
high=vari>=0.001
len(vari1)/len(X)

0.03671298107741361

In [27]:
X_high=X[high]

In [28]:
poi=[]
sig=[]
cnt=[]
iter=[]
for i in range(len(X_high)):
  boundary=find_boundary(X_high[i])
  point,signal,itera=check_uncertainty(X_high[i],0.001,boundary)
  poi.append(point)
  sig.append(signal)
  iter.append(itera)
  print(i+1,point.data[0:5],point.value,point.var,itera,signal)


1 [0. 0. 0. 2. 2.] tf.Tensor([[0.1617291]], shape=(1, 1), dtype=float32) [0.00038029] 19 True
2 [1, 3, 1, 1.0, 2.0] tf.Tensor([[0.5662073]], shape=(1, 1), dtype=float32) [0.00090206] 125 True
3 [2. 0. 0. 3. 0.] tf.Tensor([[0.1822083]], shape=(1, 1), dtype=float32) [0.00096233] 3 True
4 [3. 0. 0. 1. 2.] tf.Tensor([[0.24094546]], shape=(1, 1), dtype=float32) [0.00093821] 10 True
5 [3. 0. 0. 4. 0.] tf.Tensor([[0.28446203]], shape=(1, 1), dtype=float32) [0.00095279] 4 True
6 [0. 0. 0. 0. 0.] tf.Tensor([[0.20743033]], shape=(1, 1), dtype=float32) [0.04553846] 9 False
7 [2. 1. 1. 4. 1.] tf.Tensor([[0.51929927]], shape=(1, 1), dtype=float32) [0.00094726] 4 True
8 [0, 3, 0, 4.0, 0.0] tf.Tensor([[0.34446168]], shape=(1, 1), dtype=float32) [0.00099257] 146 True
9 [1, 1, 0, 0.0, 2.0] tf.Tensor([[0.21794054]], shape=(1, 1), dtype=float32) [0.00098527] 33 True
10 [4. 1. 1. 4. 1.] tf.Tensor([[0.5446162]], shape=(1, 1), dtype=float32) [0.00092567] 332 True
11 [0, 2, 0, 1.0, 0.0] tf.Tensor([[0.2465247

In [29]:
val_1=[]
var_1=[]
for i in range(len(X_high)):
  val_1.append(np.array(poi[i].value)[0])
  var_1.append(np.array(poi[i].var)[0])


In [30]:
var_1
np.savetxt("iter.csv", iter)

In [31]:
cn=0
for i in range(len(X_high)):
  if(sig[i]==False):
    cn+=1
print(cn/len(X_high))

0.09138321995464853


In [32]:
np.mean(iter)

47.00249433106576

In [44]:
np.max(iter)

2121

In [33]:
valcheck=np.array(val_1)

In [46]:
cn_5=0
for i in range(len(X_high)):
  if(valcheck[i]>=0.5 and sig[i]==True):
    cn_5+=1
1-cn_5/len(X_high)

0.7501133786848073

In [47]:
cn_4=0
for i in range(len(X_high)):
  if(valcheck[i]>=0.4 and sig[i]==True):
    cn_4+=1
1-cn_4/len(X_high)

0.6199546485260772

In [48]:
cn_3=0
for i in range(len(X_high)):
  if(valcheck[i]>=0.3 and sig[i]==True):
    cn_3+=1
1-cn_3/len(X_high)

0.501360544217687

In [49]:
cn_2=0
for i in range(len(X_high)):
  if(valcheck[i]>=0.2 and sig[i]==True):
    cn_2+=1
1-cn_2/len(X_high)

0.273469387755102

In [50]:
cn_1=0
for i in range(len(X_high)):
  if(valcheck[i]>=0.1 and sig[i]==True):
    cn_1+=1
1-cn_1/len(X_high)

0.11292517006802716

In [51]:
cn_0=0
for i in range(len(X_high)):
  if(valcheck[i]>=0.0 and sig[i]==True):
    cn_0+=1
1-cn_0/len(X_high)

0.09138321995464849

In [42]:
val_1=valcheck[valcheck<=0.1]

In [43]:
len(val_1)/len(X_high)

0.027664399092970523